[build]
  functions = "netlify/functions"

[dev]
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["mongoose"]  

[[scheduled]]
name = "update-purchase"
cron = "0 */4 * * *"   

[[scheduled]]
name = "update-sales"
cron= "*/15 * * * *"  
