[build]
  functions = "netlify/functions"

[dev]
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["mongoose"]  

[[scheduled]]
  name = "update-purchase-background"
  cron = "0 */4 * * *"   

[[scheduled]]
  name = "update-sales-background"
  cron = "0 * * * *" 