[build]
  functions = "netlify/functions"

[dev]
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["mongoose"]  

[[scheduled]]
name = "update-purchase-background"
cron = "0 */4 * * *"   # Run every 4 hours (e.g., 12:00, 4:00, 8:00, etc.)

[[scheduled]]
name = "update-sales-background"
cron = "30 */4 * * *"  # Run every 30 minutes, but stagger by 30 minutes (e.g., 12:30, 4:30, 8:30, etc.)
