[build]
  functions = "netlify/functions"

[dev]
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["mongoose"]  

[functions."update-purchase"]
schedule = "@hourly"

[[scheduled]]
name = "update-sales"
cron= "*/15 * * * *"  
