[build]
  functions = "netlify/functions"

[dev]
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["mongoose"]  

[functions."update-purchase"]
schedule = "0 */4 * * *"

[functions."update-sales"]
schedule= "*/30 * * * *"  

[functions."update-sync-order"]
schedule= "*/3 * * * *" 

[functions."update-process-order"]
schedule= "*/8 * * * *" 