[build]
  functions = "netlify/functions"

[dev]
  functions = "netlify/functions"

[[scheduled]]
  name = "update-purchase"
  cron = "0 */4 * * *"   

[[scheduled]]
  name = "update-sales-background"
  cron = "0 * * * *" 